Axit project
ElizabethMedvedeva/fe-46-medvedeva pull request #2
Opened 2023-02-06 18:29 UTC by ElizabethMedvedeva

2023-02-07 07:52 UTC, UladTeachMeSkills requested changes

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        </div>
Данный логотип можно было вставить одним изображением. Не исправляй.

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    </div>
nav +
 ul + 
  li + a
  li + a

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        <div class="divider" id="white__divider"></div>
Зачем тебе id? используй два класса вместе

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        </div>
Это всё - форма, используй соответствующий тег form.
Для кнопки пропиши тип submit

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                </div>
Это список с ссылками ul + li + a + img

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                </div>
Это форма - тег form.
Кнопка send essage должна иметь тип submit

2023-02-07 07:52 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    </div>
Это список с ссылками ul + li + a + img

2023-02-07 07:52 UTC, UladTeachMeSkills commented on lesson-5/index.css
> +
Почисти лишние пробелы

2023-02-07 07:52 UTC, UladTeachMeSkills commented on lesson-5/index.css
> +}
Зачем тебе пустые стили?

2023-02-07 09:25 UTC, ElizabethMedvedeva commented on lesson-5/index.css
> +}
Это из классной работы, у меня нет ссылки на макет который ты делал, там должны были быть картинки.

2023-02-08 15:23 UTC, UladTeachMeSkills approved these changes

2023-02-08 16:34 UTC, merged