add finished maket
ElizabethMedvedeva/fe-46-medvedeva pull request #4
Opened 2023-02-15 21:02 UTC by ElizabethMedvedeva

2023-02-16 08:46 UTC, UladTeachMeSkills requested changes

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +}
Используй это в отдельном общем файле стилей

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +}
В общий файл

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +}
Общий контейнер и максимальная ширина 1170

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    background-size: 1510px 1026px;
при уменьшении или увеличении размеров - полетит изображение

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    ;
лишнее

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    width: 100%px;
Выбери что-то одно или рх или %

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner.css
> +    flex-direction: row;
Не надо

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner_2.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner_2.css
> +
space

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner_2.css
> +    background-size: 1510px 442px;
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner_2.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/banner_2.css
> +    font-family: 'Raleway';
В body уже прописан font-family: 'Raleway', sans-serif;

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/contact.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/contact.css
> +    max-width: 1170px;
Зачем?

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/contact.css
> +    max-width: 1170px;
Зачем?

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/contact.css
> +    max-width: 1169px;
Зачем?

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/footer.css
> +    width: 1510px;
Фиксированный размер

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/header.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/pricing.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/pricing.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/pricing.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/pricing.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/pricing.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +}
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    flex-direction: row;
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    flex-direction: row;
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    flex-direction: row;
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/reviews.css
> +    font-family: 'Raleway';
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/tab.css
> +@import url('https://fonts.googleapis.com/css2?family=Raleway&display=swap');
same

2023-02-16 08:46 UTC, UladTeachMeSkills commented on finished axit-project/styles/tab.css
> +    font-family: 'Open Sans', sans-serif;
У тебя всё время дефолтным шрифтом было font-family: 'Raleway', sans-serif; а тут ты его переопределила

2023-02-16 14:58 UTC, ElizabethMedvedeva commented on finished axit-project/styles/awesome.css
> +}
изменить max-width для .awesome__container или создать общий для всех секций и ему дать такое значение?

2023-02-17 08:45 UTC, UladTeachMeSkills requested changes

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +    <link href="./styles/style.css" rel="stylesheet">
Попробуй подключить все свои файлы стилей в один "сборщик" это index.css при помощи @import(link)
Подключи один единственный файл index.css при помощи link в свой файл index.html

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +                    </div>
Можно экспортировать из фигмы одним файлом изображения, так будет проще их регулировать на странице

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +        </div>
Проверь, возможно есть лишний закрывающий тег

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +                                <img src="./img/Rectangle 111.png" alt="statue">
Пробелы в имени файла

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +                                <img src="./img/Rectangle 111.png" alt="statue">
same

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +                                <img src="./Rectangle 111.png" alt="statue">
same

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +    <script src="./tab.js"></script>
Подключи в конце страницы

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +        </div>
Хмм

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +        <!--<div class="contact__wrapper">-->
Убери если не нужно

2023-02-17 08:45 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +        <!--</div>-->
same

2023-02-17 08:53 UTC, UladTeachMeSkills commented on finished axit-project/styles/awesome.css
> +}
Контейнер который имеет 
 max-width: 1150px;
 margin: 0 auto;
 
 будет общим для всех, под именем .container

2023-02-17 09:20 UTC, ElizabethMedvedeva commented on finished axit-project/styles/footer.css
> +    width: 1510px;
если ставлю max-width то значки слипаются и никак не получается их разлепить

2023-02-17 09:37 UTC, ElizabethMedvedeva commented on finished axit-project/styles/banner.css
> +    background-size: 1510px 1026px;
как корректно это оформить?

2023-02-17 15:12 UTC, ElizabethMedvedeva commented on finished axit-project/axit.html
> +    <script src="./tab.js"></script>
т.е. в body но в самый конец?

2023-02-19 15:32 UTC, UladTeachMeSkills approved these changes

2023-02-19 15:32 UTC, UladTeachMeSkills commented on finished axit-project/axit.html
> +                        </div>
Можно экспортировать из фигмы одним изображением, так будет проще

2023-02-19 15:32 UTC, UladTeachMeSkills commented on finished axit-project/styles/contact.css
> +  width: 571px;
Попробуй использовать ширину 100%, при этом родителю пропиши заполнение пустого пространства при помощи flex. Таким образом у тебя отпадёт необходимость контролировать фиксированную ширину при уменьшении и увеличении размеров. Сделай так со всеми инфутами.

2023-02-19 15:32 UTC, UladTeachMeSkills commented on finished axit-project/styles/footer.css
> +  width: 1510px;
Надо как-то избавиться

2023-02-19 15:32 UTC, UladTeachMeSkills commented on finished axit-project/styles/footer.css
> +  height: 164px;
Нужно что-то другое

2023-02-21 07:55 UTC, UladTeachMeSkills approved these changes

2023-02-22 17:55 UTC, merged